services:
  postgres:
    container_name: postgres_db
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/postgres
    deploy:
      replicas: ${ENABLE_POSTGRES}

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: ["npm", "run", "dev"]

volumes:
  postgres_data:
